---
# This playbook deploys the whole application stack in this site 

- name: apply common configuration
  hosts: webservers dbservers
  remote_user: lukas
  become: yes

  roles:
    - common

- name: configure and deploy the webserver and application code
  hosts: webservers
  remote_user: lukas
  become: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  remote_user: lukas
  become: yes

  roles:
    - db
