---
- hosts: scotlandia
  remote_user: lukas
  become: yes
  tasks:
    - name: apt-get update
      apt:
        update-cache: yes
      changed_when: 0

    - name: get list of pending upgrades
      command: apt-get --simulate dist-upgrade
      args:
        warn: false # don't warn us about apt having its own plugin
      register: apt_simulate
      changed_when: 0

      # - name: parse apt-get output to get list of changed packages
      #set_fact:
      #  updates: '{{ apt_simulate.stdout_lines | select("match", "^Inst ") | list | splitpart(1, " ") | list | sort }}'
      #changed_when: 0

    - name: show pending updates
      debug:
        var: updates
      when: updates.0 is defined

    - name: apt-get autoremove
      command: apt-get -y autoremove
      args:
        warn: false
      when: '"Inst linux-image-" in apt_simulate.stdout'
      changed_when: 0

    # do the actual apt-get dist-upgrade
    - name: apt-get dist-upgrade
      apt:
        upgrade: dist # upgrade all packages to latest version
      register: upgrade_output

    # check if we need a reboot
    - name: check if reboot needed
      stat: path=/var/run/reboot-required
      register: file_reboot_required

    # here starts the actual install previous was updates/upgrades
    - name: checking if apache2 is installed
      apt:
        name: apache2
        state: present
    - name: checking if mysql is installed
      apt:
        name: mysql-server
        state: present
    - name: checking if php is installed
      apt:
        name: php libapache2-mod-php php-mcrypt php-mysql
        state: present

    - name: checking if apache2 is running
      service:
        name: apache2
        state: started
    - name: checking if mysql is running
      service:
        name: mysql-server
        state: started
    - name: checking if php is running
      service:
        name: php
        state: started

